name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Clean working directory
        run: git clean -fd

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: lucascodev
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Add and Commit Generated Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/*
          git commit -m "Generated Snake Animation"

      - name: Push Changes to Outputs Branch
        run: |
          git push origin HEAD:outputs --force
