name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch: # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Compatível com o snk

      - name: Install snk and generate animation
        run: |
          npm install -g @platane/snk@3 # Instala a biblioteca corretamente
          snk generate --user-name lucascodev --output dist/github-snake.svg
          snk generate --user-name lucascodev --palette github-dark --output dist/github-snake-dark.svg
          snk generate --user-name lucascodev --output dist/ocean.gif --color-snake orange --color-dots "#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"

      - name: Commit and Push Snake Animation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated Snake Animation"
          branch: outputs
          file_pattern: "dist/*"
