name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: lucascodev
          outputs: |
            dist/github-user-contribution.svg
            dist/github-user-contribution-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
